type User {
  id: ID!
  email: String!
  password: String!
}

extend type Query {
  currentUser: User
  users: [User]
}

extend type Mutation {
  createUser(email: String!, password: String!): String
  login(email: String!, password: String): String
}
