module.exports = {
  TICKET_ADDED: 'TICKET_ADDED',
  TICKET_REMOVED: 'TICKET_REMOVED',
  TICKET_UPDATED: 'TICKET_UPDATED',

  BOARD_ADDED: 'BOARD_ADDED',
  BOARD_REMOVED: 'BOARD_REMOVED',
  BOARD_UPDATED: 'BOARD_UPDATED',
};
